server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cloudblog_user?serverTimezone=GMT
    hikari:
      username: root
      password: 116924
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: user-service

