server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cloudblog?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    hikari:
      username: root
      password: 116924
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: blog-user-topic
          group: blog-user-binding
  application:
    name: user-service
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
