server:
  port: 8041
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #geteway通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: between_route
          uri: lb://user-service
          predicates:
            - TimeBetween=上午9:00,下午9:00

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always